ifneq (override,$(origin TOP))

# project configuration file

override CLEAN_BUILD_REQUIRED_VERSION := 0.3.2

# project root directory
# note: override always, because TOP is auto-defined
override TOP := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

# supported build types
# note: override clean-build defaults set in $(MTOP)/defs.mk
override SUPPORTED_TARGETS := DEBUG RELEASE

# do not inherit variable from environment
TARGET:=

# if TARGET is not specified in command line, set default
ifndef TARGET
# note: override clean-build defaults set in $(MTOP)/defs.mk
override TARGET := RELEASE
endif

# default value for MODVER
# major.minor.patch
# note: override clean-build defaults set in $(MTOP)/defs.mk
override PRODUCT_VER := 1.0.3

# header generated by $(MTOP)/exts/version/version.mk
# $(PRODUCT_NAMES_H) - used in $(MTOP)/WINXX/cres.mk
PRODUCT_NAMES_H := vers.h

# version info for a dll, also needed by $(MTOP)/exts/version/version.mk
VENDOR_NAME      := Michael M. Builov
VENDOR_URL       := https://github.com/mbuilov/memstack
PRODUCT_NAME     := Memory Stack allocation library
VENDOR_COPYRIGHT := Copyright (C) 2008-2017 $(VENDOR_NAME), $(VENDOR_URL)

# licence for generated pkgconfig .pc file
PRODUCT_LICENCE  := LGPL version 2.1 or any later version

# library name
MEMSTACK_LIB_NAME := memstack$(if $(filter DEBUG,$(TARGET)),d)

# variants of built static library
#  LINUX:
#   R,S   - position-dependent code
#   P     - position-independent code for executables
#   D     - position-independent code for shared objects (dlls)
#  WINDOWS:
#   R,P,D - dynamically linked multi-threaded libc
#   S     - statically linked multi-threaded libc
MEMSTACK_LIB_VARIANTS := R P D S

# variants of built dynamic library
#  LINUX:
#   R,S   - position-independent code
#  WINDOWS:
#   R     - dynamically linked multi-threaded libc
#   S     - statically linked multi-threaded libc
MEMSTACK_DLL_VARIANTS := R S

# by default, build and install both shared and static variants of the library
NO_SHARED:=
NO_STATIC:=

# MTOP - path to clean-build - must be defined either in command line or in $(TOP)/conf.mk
# note: do not inherit MTOP value from environment
MTOP:=

# override defaults, if $(TOP)/conf.mk was generated
-include $(TOP)/conf.mk

# clean-build path must be defined
ifndef MTOP
$(error MTOP - path to clean-build (https://github.com/mbuilov/clean-build) is not defined,\
 example: MTOP=/usr/local/clean-build or MTOP=C:\User\clean-build)
endif

ifeq (WINXX,$(OS))
override PREDEFINES = $(call lazy_simple,override PREDEFINES,$(if $(DEBUG),_DEBUG) $(OS_PREDEFINES))
endif

endif
